#!/bin/sh
#
# Gradle start up script for POSIX generated by Gradle.
#

# Attempt to set APP_HOME
SAVED="`pwd`"
cd "`dirname \"$0\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

warn () {
    echo "$*"
} >&2

if [ "$1" = "" ] ; then
    die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
fi

JAVACMD="java"

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn_wrong_java_version () {
    warn "WARNING: Version $1 of Java found on your system."
}

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

exec "$JAVACMD" "${DEFAULT_JVM_OPTS}" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
